[program:stock-ai]
command=python /var/www/stock-ai/stock_app.py
directory=/var/www/stock-ai
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/stock-ai.err.log
stdout_logfile=/var/log/stock-ai.out.log
environment=PYTHONPATH="/var/www/stock-ai"
